### ISSUE TITLE
Feature request: set charging threshold for hiding

### ISSUE THREAD

**Issue by bam80** [ai/autohide-battery#10]
I use feature of my laptop to not fully charge even on AC, so charging stops at ~60% for battery livelong.

Could we have a threshold to set for hiding the icon?
Thanks.

**Comment by ai** [comment]
I (as author) want this feature too, but have no idea how to implement it.

**Comment by bam80** [comment]
What do you mean? Can't we just have configurable parameter here instead of 100%?
https://github.com/ai/autohide-battery/blob/84b577aa3c10ca6737e9a655b4f86c20b9e5eb2b/extension.js#L38

**Comment by ai** [comment]
I do not like an option because it is a hacky way.

I set laptop settings to stop charging at 80%, but GNOME shows me 79%.

However, if there is no other way we can do it with manual settings. Do you want to create PR (I have no experience with creating settings for GNOME extension).

**Comment by bam80** [comment]
Oh, sorry I don't have experience in JS at all :)
About the percentage, I think we could set up a "sweet spot" to hide the icon, i.e
```js
79 <= proxy.Percentage <= 80

**Comment by bam80** [comment]
Maybe this extension could be simple settings example?
https://github.com/laserb/gnome-shell-extension-suspend-button

**Comment by ai** [comment]
Oh. It is a lot of code. I am not sure that I will have time in the next few months (need to finish other open-source tasks).

**Comment by ai** [comment]
Done 3b82790

**Comment by bam80** [comment]
Thanks a lot!
