### ISSUE TITLE
Deprecation warning from indicators

### ISSUE THREAD

**Issue by Spurlos** [ai/autohide-battery#12]
> Aug 18 17:21:56 spurlos-ThinkPad-E580 gnome-shell[2971]: Usage of indicator.indicators is deprecated for Indicator#012get indicators@resource:///org/gnome/shell/ui/panelMenu.js:213:25#012getBattery@/home/spurlos/.local/share/gnome-shell/extensions/autohide-battery@sitnik.ru/extension.js:41:5#012hide@/home/spurlos/.local/share/gnome-shell/extensions/autohide-battery@sitnik.ru/extension.js:16:3#012update/<@/home/spurlos/.local/share/gnome-shell/extensions/autohide-battery@sitnik.ru/extension.js:29:7#012getBattery@/home/spurlos/.local/share/gnome-shell/extensions/autohide-battery@sitnik.ru/extension.js:41:5#012update@/home/spurlos/.local/share/gnome-shell/extensions/autohide-battery@sitnik.ru/extension.js:23:3#012enable@/home/spurlos/.local/share/gnome-shell/extensions/autohide-battery@sitnik.ru/extension.js:50:3#012_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:122:49#012_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:505:18#012_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:504:21#012_init/ceateCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46#012disableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:209:29#012DisableExtension@resource:///org/gnome/shell/ui/shellDBus.js:311:38#012_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34

Seems that some code is getting old.

**Comment by ai** [comment]
Seems like it is happens because of this line https://github.com/ai/autohide-battery/blob/master/extension.js#L41

Do you know how to update the API?

**Comment by Spurlos** [comment]
After a quick search over other extensions I think i have found the new way of using that API:
https://github.com/home-sweet-gnome/dash-to-panel/commit/ed3c3e072e55a3c00e2f0a3ab8f810a36bce2c2c#diff-2599b72aecbef8f8725aa5c4bf2fc0a0L1121

**Comment by ai** [comment]
Fixed 7f34be8]

Thanks for finding the solution

**Comment by ai** [comment]
I pish new 17 version to GNOME Extensions
