### ISSUE TITLE
Fails to work with Gnome 3.16

### ISSUE THREAD

**Issue by GeraldPfeifer** [ai/autohide-battery#3]
This worked like a charm with Gnome 3.12 and 3.14. I just updated to Gnome 3.16
on openSUSE Factory/Tumbleweed and extensions.gnome.org listed this extension
as outdated (and indeed it fails to work).

**Comment by ai** [comment]
Wait a few minutes, I update manifest

**Comment by ai** [comment]
I add new version to extentions site. Please try again.

**Comment by GeraldPfeifer** [comment]
Very cool, thanks for the fast response! (I just updated and can confirm it works now.)
