### ISSUE TITLE
Hide battery icon if battery is charged above (value in % which may be set by user) and AC is disconnected

### ISSUE THREAD

**Issue by ardnod** [ai/autohide-battery#59]
For example: 30% or 20%.
I want this feature, because my laptop works long on battery.

**Comment by ai** [comment]
It is exactly how it should work right now
https://github.com/ai/autohide-battery/blob/main/extension.js#L83-L85

**Comment by ardnod** [comment]
When I plug in AC battery icon dissapear.
I want see battery only when battery is low charged.
When I don't have battery (e.g. in computer) I have other extension to hide "power" icon on panel.

**Comment by ai** [comment]
The extension already have a setting to set minimum battery level when icon will be hidden.

```js
if (proxy.Percentage >= hideOn) {
  this.hide()
}
```

1. Be sure that you are using the latest version of the extension.
2. Open extension’s settings and set `20%`
3. Close extensions settings to apply new number

**Comment by ardnod** [comment]
I want option to hide battery icon when AC is disconnected.

**Comment by ai** [comment]
It should hide battery icon. The `if` block I send you doesn’t check if AC is connected or not, it just checks battery level against the level from settings.

Please show how these settings works on your machine.

Maybe you are using GNOME <45? In this case you are using old version of extension.

**Comment by ardnod** [comment]
It is a small, but good thing.
GNOME 45... Ubuntu 23.10.
I have 44.9.
I don't want to try anything else.
So, I wait for 2025.
"I will survive" :)
This issue can be closed.

**Comment by ardnod** [comment]
Could You delete this topic?
