### ISSUE TITLE
Battery icon not showing when device is unplugged

### ISSUE THREAD

**Issue by suvanbanerjee** [ai/autohide-battery#60]
### Current behavior 
my battery stops charging at 90% (battery health feature) so i have put my full charge limit at 90% but if my battery is more than 90% it hides battery icon regardless of the charging state

### Expected behavior
It should only hide the battery icon when device is plugged.

**Comment by ai** [comment]
Unfortunately, battery health feature on some laptops reports a wrong state

**Comment by suvanbanerjee** [comment]
i think the issue is not about battery health. we can check the discharging state and set it to show battery icon if device is discharging. 

I have fixed it on my local device and will attach a PR of that in this issue. do check it
