### ISSUE TITLE
Add options for threshold for hiding?

### ISSUE THREAD

**Issue by b3nis** [ai/autohide-battery#66]
Hey!

Thanks for making this extensions! 

I got a feature request: how about adding an option to set a threshold for hiding? Like "if it's over 80%" = hide the battery icon.

Take care!

**Comment by ai** [comment]
We already have similar option. Is it not working for you?

**Comment by b3nis** [comment]
Gah. Sorry, my brain is out of order. I do see it now.

Then I just say thank you for amazing work!
