### ISSUE TITLE
Not hide battery indicator.

### ISSUE THREAD

**Issue by AlexGluck** [ai/autohide-battery#7]
OS Fedora 26, Gnome 3.24 and listing extensions below:
```
AlternateTab
Arc Menu
Caffeine
Dash to Panel
Disable Barrier Support
Disconnect Wifi
Extend Panel Menu
Extended Gestures
Extension Update Notifier
Imgur Screenshot Uploader
KStatusNotifierItem/AppIndicator Support
No Topleft Hot Corner
NoAnnoyance
Panel OSD
Permanent notifications
Refresh Wifi Connections
Remmina Search Provider
Removable Drive Menu
Remove Dropdown Arrows
Status Area Horizontal Spacing
TopIcons Plus
Transcode App Search
Trash
User Themes
```

**Comment by ai** [comment]
Oh. I will update to Gnome 3.24 only in next month.

Maybe you can debug extension code?

**Comment by AlexGluck** [comment]
What need to do?

**Comment by AlexGluck** [comment]
Может по русски?

**Comment by AlexGluck** [comment]
На федоре 25, гном 3.22 там тоже не работало. Там уже не продебажу.

**Comment by ai** [comment]
1. Вызови Looking Glass https://stackoverflow.com/questions/8425616/how-to-test-debug-gnome-shell-extensions-is-there-any-tool-for-that
2. Посмотри чему равно `UPower.DeviceKind.BATTERY` и `UPower.DeviceState.FULLY_CHARGED`

**Comment by ai** [comment]
> На федоре 25, гном 3.22 там тоже не работало

Вот это уже странно. У меня работает. А если оключить все расширения? Может это конфликт?

**Comment by AlexGluck** [comment]
На 25 откатываться уже не буду, вот из lg скрин
![2017-07-19 19-06-43](https://user-images.githubusercontent.com/8583390/28377455-76066932-6cb5-11e7-89f5-7c8577d68d3f.png)

**Comment by AlexGluck** [comment]
Вот вывод монитора upower
```
[alexgluck@gluck-laptop ~]$ upower -m
Monitoring activity from the power daemon. Press Ctrl+C to cancel.
[18:37:03.341]	device changed:     /org/freedesktop/UPower/devices/battery_BAT0
[18:37:03.342]	device changed:     /org/freedesktop/UPower/devices/battery_BAT0
[18:37:03.342]	device changed:     /org/freedesktop/UPower/devices/battery_BAT0
[18:37:03.343]	device changed:     /org/freedesktop/UPower/devices/line_power_AC0
[18:37:03.343]	device changed:     /org/freedesktop/UPower/devices/line_power_AC0
[18:37:03.344]	daemon changed:
[18:37:06.974]	device changed:     /org/freedesktop/UPower/devices/battery_BAT0
[18:37:06.974]	device changed:     /org/freedesktop/UPower/devices/battery_BAT0
[18:37:06.974]	device changed:     /org/freedesktop/UPower/devices/battery_BAT0
[18:37:06.975]	device changed:     /org/freedesktop/UPower/devices/line_power_AC0
[18:37:06.975]	device changed:     /org/freedesktop/UPower/devices/line_power_AC0
[18:37:06.976]	daemon changed:
[18:37:07.082]	device changed:     /org/freedesktop/UPower/devices/battery_BAT0

```

**Comment by AlexGluck** [comment]
Если это важно то я на xorg а не wayland

**Comment by ai** [comment]
Упс, вместо `UPower` `imports.ui.status.power.UPower`

И попробуй отключить все расширения. Если на старом GNOME тоже не работало, то значит проблема не в смене API.

**Comment by AlexGluck** [comment]
![2017-07-19 19-43-21](https://user-images.githubusercontent.com/8583390/28378909-922e61e6-6cba-11e7-9153-9a8e530cac6c.png)

**Comment by ai** [comment]
Значит АПИ не менялся. Теперьпопробуй отключить все остальные расширения.

**Comment by AlexGluck** [comment]
Не помогло.

**Comment by ai** [comment]
Честно говоря, нет идей :(.

Попробуй другое расширение: https://extensions.gnome.org/extension/817/battery-status/

**Comment by AlexGluck** [comment]
Тоже не работает, пробовал.

**Comment by AlexGluck** [comment]
Ладно и на этом спасибо. Если починишь свистни, закину на пиво.

**Comment by ai** [comment]
Если у тебя глючат сразу 2 расширения — то это очень-очень странно. Скорее всего проблема, где в другом месте

**Comment by AlexGluck** [comment]
Согласен, но как решить быстро я не знаю. А задача явно на длительное вкуривание, автоскрытие иконки аккумулятора не настолько важно. Всё остальное работает исправно или приемлемо. Вот сворачиваемый трей жду когда кто нибудь на гном3 привезёт.
![2017-07-19 20-29-36](https://user-images.githubusercontent.com/8583390/28380727-119fa2cc-6cc1-11e7-80bc-4637970f77f5.png)

**Comment by AlexGluck** [comment]
Запилили скрытие батареи в этом [расширении](https://github.com/julio641742/extend-panel-menu)
