### ISSUE TITLE
Repeated display and hiding of battery icon

### ISSUE THREAD

**Issue by amitbha** [ai/autohide-battery#8]
Because of the aging of the laptop battery, sometimes the battery level jumps between 100% and 98%,  leading to repeated display and hiding of battery icon.
Please add a threshold setting, hide the icon as long as the battery level reaches a certain value.
Thanks a lot!

**Comment by ai** [comment]
Can you send PR?

**Comment by ai** [comment]
Done 3b82790

**Comment by amitbha** [comment]
I use i3wm instead of gnome-shell now 😅
